apiVersion: apps/v1
kind: Deployment
metadata:
    name: tempberry-backend
    labels:
        app: tempberry-backend
spec:
    replicas: {{ .Values.replicaCount }}
    selector:
        matchLabels:
            app: tempberry-backend
    template:
        metadata:
            labels:
                app: tempberry-backend
                app.kubernetes.io/name: {{ .Values.keptn.service }}
                app.kubernetes.io/instance: "{{ .Values.keptn.service }}-{{ .Values.keptn.deployment }}"
                app.kubernetes.io/component: api
                app.kubernetes.io/part-of: "{{ .Chart.Name }}" # = Keptn Project
                app.kubernetes.io/managed-by: Keptn
        spec:
            containers:
                - name: tempberry-backend
                  image: "{{ .Values.image }}"
                  imagePullPolicy: Always
                    # remove comment in next line to pull image from local cache
                    # imagePullPolicy: Never
                  ports:
                      - containerPort: 8000
                  env:
                      - name: DT_CUSTOM_PROP
                        value: "keptn_project={{ .Values.keptn.project }} keptn_service={{ .Values.keptn.service }} keptn_stage={{ .Values.keptn.stage }} keptn_deployment={{ .Values.keptn.deployment }}"
                      - name: DATABASE_USER
                        valueFrom:
                            secretKeyRef:
                                name: postgres-credentials
                                key: user

                      - name: DATABASE_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: postgres-credentials
                                key: password

                      - name: DATABASE_NAME
                        value: "tempberry"

                      - name: DATABASE_HOST
                        value: "postgres"

                      - name: DATABASE_PORT
                        value: "5432"

                      - name: DATABASE_URL
                        value: postgres://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOST)/$(DATABASE_NAME)

                      - name: DJANGO_SETTINGS_MODULE
                        value: "tempBerry.settings.live"

                      - name: DJANGO_ALLOWED_HOSTS
                        value: "*"

                      - name: SECRET_KEY
                        value: "TODO_ADD_KEY_HERE"
                  resources:
                    limits:
                      cpu: 500m
                      memory: 256Mi
                    requests:
                      cpu: 100m
                  livenessProbe:
                    httpGet:
                      path: /api/
                      port: 8000
                    initialDelaySeconds: 10
                    periodSeconds: 10
                    timeoutSeconds: 15
                  readinessProbe:
                    httpGet:
                      path: /api/
                      port: 8000
                    initialDelaySeconds: 10
                    periodSeconds: 10
                    timeoutSeconds: 15
